url: "http://wu-researchgroup.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Multiphysics Fluid-Structure Interaction Research Laboratory" # the name of your site, e.g. ACME Corp.
description: "@ MAE | HKUST"

# Homepage limit posts
number_of_posts: 5
number_of_menu_items: 4
